In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[34,45,67,98],[3,4,56,6]])
print(b)

[[34 45 67 98]
 [ 3  4 56  6]]


# get dimension
# for finding the dimension  use  "ndim"

In [4]:
a.ndim

1

# get shape 
# for finding the dimension use "shape"

In [5]:
a.shape

(3,)

In [6]:
b.shape

(2, 4)

# get type
# for finding the type use "dtype"

In [7]:
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('int32')

# get size 
# In int 16 - the item size will be 16
# In int 32 - the item size will be 32

In [9]:
a.itemsize
b.itemsize

4

In [10]:
# get totalsize
a.size * a.itemsize
# another way of doing it is 
a.nbytes


12

Accessing /changing  specfic elements ,rows ,columns etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# to get a specific element [r,c]
a[1,5]

13

In [13]:
# get a specific row

a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [14]:
# get a specific column
a[:,2]


array([ 3, 10])

In [15]:
# getting a little more fancy[startindex:endindex:stepsize]

a[0, 1:6:2]


array([2, 4, 6])

In [16]:
a[1,5] = 20
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
n =np.array([[[1,2],[3,4],[5,6]]])
print(n)

[[[1 2]
  [3 4]
  [5 6]]]


In [18]:
# get specific element (work outside in)
n[0,1,1]

4

Intializing Different Types of Arrays

In [19]:
#All zeros in matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [20]:
# All ones in matrix
np.ones((4,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [21]:
# Any other number
np.full((2,2),99)


array([[99, 99],
       [99, 99]])

In [22]:
# Any other number (full_like)

np.full_like(a.shape, 4)


array([4, 4])

In [23]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [24]:
# Random decimal numbers 
np.random.rand(4,2)

array([[0.08129301, 0.50046288],
       [0.03310449, 0.63986905],
       [0.8088197 , 0.11399546],
       [0.68133891, 0.50143854]])

In [25]:
# random integers 
np.random.randint(7)

1

In [26]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# repeating the array
arr = np.array([1,2,3])
r1 =np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [28]:
arr = np.array([[1,2,3]])
r1 =np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [29]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output [1:4,1:4] = z
print(output)

# be careful while copying arrays 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
a = np.array([1,2,3])
b=a
b[0] = 100
print(b)
print(a)

# if we do this there will be a problem a and b will be same but we only changed the value of b,so we when we print a it will also print [100,2,3]
# to avoid this  we will use b = a.copy()
# lets run this whole a.copy into a new command


[100   2   3]
[100   2   3]


In [31]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(b)
print(a)
# now b will print [100,2,3] and a will print [1,2,3]


[100   2   3]
[1 2 3]


# mathematics

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
a + 2

array([3, 4, 5, 6])

In [34]:
a - 2

array([-1,  0,  1,  2])

In [35]:
a -2

array([-1,  0,  1,  2])

In [36]:
a * 2

array([2, 4, 6, 8])

In [37]:
a /2 

array([0.5, 1. , 1.5, 2. ])

In [38]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [39]:
a ** 2

array([ 1,  4,  9, 16])

In [40]:
# take the sin of all the values
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [42]:
np.tan(a)


array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# linear Algebra

In [43]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
c = np.identity(3)
np.linalg.det(c)

1.0

# In linear algebra you can also do these things 

# determinant
# trace
# singular vector decomposition
# Eigen values
# Matrix form
# Inverse

# statistics

In [45]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)

1

In [47]:
np.max(stats)

6

In [48]:
np.min(stats, axis=1)

array([1, 4])

In [49]:
np.max(stats,axis=1)

array([3, 6])

In [50]:
np.max(stats,axis=0)


array([4, 5, 6])

In [51]:
np.min(stats,axis=0)

array([1, 2, 3])

In [52]:
np.sum(stats)

21

# Reorganizing Arrays

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

# lets make this 2 by 4 into 8 by 1

after = before.reshape((8,1))
print(after)




(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [54]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

Load data from file